[2023-02-22T16:21:57.117+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: csv_from_s3_to_s3_v01.test_connection manual__2023-02-22T16:21:55.550221+00:00 [queued]>
[2023-02-22T16:21:57.129+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: csv_from_s3_to_s3_v01.test_connection manual__2023-02-22T16:21:55.550221+00:00 [queued]>
[2023-02-22T16:21:57.130+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-22T16:21:57.130+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-22T16:21:57.131+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-22T16:21:57.142+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): test_connection> on 2023-02-22 16:21:55.550221+00:00
[2023-02-22T16:21:57.155+0000] {standard_task_runner.py:55} INFO - Started process 8383 to run task
[2023-02-22T16:21:57.162+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'csv_from_s3_to_s3_v01', 'test_connection', 'manual__2023-02-22T16:21:55.550221+00:00', '--job-id', '213', '--raw', '--subdir', 'DAGS_FOLDER/dag_cleaning_via_s3.py', '--cfg-path', '/tmp/tmp055e6wfg']
[2023-02-22T16:21:57.168+0000] {standard_task_runner.py:83} INFO - Job 213: Subtask test_connection
[2023-02-22T16:21:57.265+0000] {task_command.py:388} INFO - Running <TaskInstance: csv_from_s3_to_s3_v01.test_connection manual__2023-02-22T16:21:55.550221+00:00 [running]> on host 22976f44c0e9
[2023-02-22T16:21:57.342+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_from_s3_to_s3_v01
AIRFLOW_CTX_TASK_ID=test_connection
AIRFLOW_CTX_EXECUTION_DATE=2023-02-22T16:21:55.550221+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-22T16:21:55.550221+00:00
[2023-02-22T16:21:57.352+0000] {base.py:73} INFO - Using connection ID 'AWS' for task execution.
[2023-02-22T16:21:57.353+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='AWS', conn_type='aws') credentials retrieved from login and password.
[2023-02-22T16:21:58.851+0000] {python.py:177} INFO - Done. Returned value was: s3.Object(bucket_name='s-tl-test', key='titanic.csv')
[2023-02-22T16:21:58.863+0000] {xcom.py:635} ERROR - Object of type s3.Object is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2023-02-22T16:21:58.864+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2297, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 240, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 170, in default
    return super().default(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type s3.Object is not JSON serializable
[2023-02-22T16:21:58.874+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=csv_from_s3_to_s3_v01, task_id=test_connection, execution_date=20230222T162155, start_date=20230222T162157, end_date=20230222T162158
[2023-02-22T16:21:58.882+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 213 for task test_connection (Object of type s3.Object is not JSON serializable; 8383)
[2023-02-22T16:21:58.929+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-22T16:21:58.957+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
