[2023-02-15T09:16:55.718+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Dag_with_dependencies_v1.0.get_sklearn manual__2023-02-15T09:16:54.295928+00:00 [queued]>
[2023-02-15T09:16:55.730+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Dag_with_dependencies_v1.0.get_sklearn manual__2023-02-15T09:16:54.295928+00:00 [queued]>
[2023-02-15T09:16:55.731+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-15T09:16:55.731+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 6
[2023-02-15T09:16:55.732+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-15T09:16:55.753+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): get_sklearn> on 2023-02-15 09:16:54.295928+00:00
[2023-02-15T09:16:55.767+0000] {standard_task_runner.py:55} INFO - Started process 19763 to run task
[2023-02-15T09:16:55.786+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Dag_with_dependencies_v1.0', 'get_sklearn', 'manual__2023-02-15T09:16:54.295928+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_dependencies.py', '--cfg-path', '/tmp/tmpkujmws4j']
[2023-02-15T09:16:55.789+0000] {standard_task_runner.py:83} INFO - Job 109: Subtask get_sklearn
[2023-02-15T09:16:55.958+0000] {task_command.py:388} INFO - Running <TaskInstance: Dag_with_dependencies_v1.0.get_sklearn manual__2023-02-15T09:16:54.295928+00:00 [running]> on host 01550fe0586b
[2023-02-15T09:16:56.120+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=tlysenko
AIRFLOW_CTX_DAG_ID=Dag_with_dependencies_v1.0
AIRFLOW_CTX_TASK_ID=get_sklearn
AIRFLOW_CTX_EXECUTION_DATE=2023-02-15T09:16:54.295928+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-15T09:16:54.295928+00:00
[2023-02-15T09:16:56.125+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_dependencies.py", line 14, in get_sklearn
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2023-02-15T09:16:56.141+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=Dag_with_dependencies_v1.0, task_id=get_sklearn, execution_date=20230215T091654, start_date=20230215T091655, end_date=20230215T091656
[2023-02-15T09:16:56.164+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 109 for task get_sklearn (No module named 'sklearn'; 19763)
[2023-02-15T09:16:56.250+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-15T09:16:56.321+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
