[2023-02-20T17:52:20.658+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: csv_to_postgres_v01.df_to_postgres manual__2023-02-20T17:52:15.562561+00:00 [queued]>
[2023-02-20T17:52:20.671+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: csv_to_postgres_v01.df_to_postgres manual__2023-02-20T17:52:15.562561+00:00 [queued]>
[2023-02-20T17:52:20.672+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-20T17:52:20.673+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-02-20T17:52:20.674+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-20T17:52:20.689+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): df_to_postgres> on 2023-02-20 17:52:15.562561+00:00
[2023-02-20T17:52:20.699+0000] {standard_task_runner.py:55} INFO - Started process 3221 to run task
[2023-02-20T17:52:20.708+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'csv_to_postgres_v01', 'df_to_postgres', 'manual__2023-02-20T17:52:15.562561+00:00', '--job-id', '165', '--raw', '--subdir', 'DAGS_FOLDER/clean_csv_via_s3_and_postgres.py', '--cfg-path', '/tmp/tmpf3kmahii']
[2023-02-20T17:52:20.711+0000] {standard_task_runner.py:83} INFO - Job 165: Subtask df_to_postgres
[2023-02-20T17:52:20.809+0000] {task_command.py:388} INFO - Running <TaskInstance: csv_to_postgres_v01.df_to_postgres manual__2023-02-20T17:52:15.562561+00:00 [running]> on host c2aaa60a62e5
[2023-02-20T17:52:20.900+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_to_postgres_v01
AIRFLOW_CTX_TASK_ID=df_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-02-20T17:52:15.562561+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-20T17:52:15.562561+00:00
[2023-02-20T17:52:20.902+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/clean_csv_via_s3_and_postgres.py", line 65, in df_to_postgres
    df = retrive_s3_to_df(file_name)
TypeError: retrive_s3_to_df() takes 0 positional arguments but 1 was given
[2023-02-20T17:52:20.914+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=csv_to_postgres_v01, task_id=df_to_postgres, execution_date=20230220T175215, start_date=20230220T175220, end_date=20230220T175220
[2023-02-20T17:52:20.925+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 165 for task df_to_postgres (retrive_s3_to_df() takes 0 positional arguments but 1 was given; 3221)
[2023-02-20T17:52:20.959+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-20T17:52:21.008+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
