[2023-02-20T17:55:54.276+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: csv_to_postgres_v01.df_to_postgres manual__2023-02-20T17:55:48.562046+00:00 [queued]>
[2023-02-20T17:55:54.282+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: csv_to_postgres_v01.df_to_postgres manual__2023-02-20T17:55:48.562046+00:00 [queued]>
[2023-02-20T17:55:54.283+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-20T17:55:54.283+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-20T17:55:54.284+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-20T17:55:54.292+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): df_to_postgres> on 2023-02-20 17:55:48.562046+00:00
[2023-02-20T17:55:54.297+0000] {standard_task_runner.py:55} INFO - Started process 3738 to run task
[2023-02-20T17:55:54.301+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'csv_to_postgres_v01', 'df_to_postgres', 'manual__2023-02-20T17:55:48.562046+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/clean_csv_via_s3_and_postgres.py', '--cfg-path', '/tmp/tmpdhjia7or']
[2023-02-20T17:55:54.302+0000] {standard_task_runner.py:83} INFO - Job 170: Subtask df_to_postgres
[2023-02-20T17:55:54.357+0000] {task_command.py:388} INFO - Running <TaskInstance: csv_to_postgres_v01.df_to_postgres manual__2023-02-20T17:55:48.562046+00:00 [running]> on host c2aaa60a62e5
[2023-02-20T17:55:54.410+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_to_postgres_v01
AIRFLOW_CTX_TASK_ID=df_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-02-20T17:55:48.562046+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-20T17:55:48.562046+00:00
[2023-02-20T17:55:54.419+0000] {base.py:73} INFO - Using connection ID 'AWS' for task execution.
[2023-02-20T17:55:54.420+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='AWS', conn_type='aws') credentials retrieved from login and password.
[2023-02-20T17:55:55.085+0000] {python.py:177} INFO - Done. Returned value was: Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'Siblings/Spouses Aboard',
       'Parents/Children Aboard', 'Fare'],
      dtype='object')
[2023-02-20T17:55:55.095+0000] {xcom.py:635} ERROR - Object of type Index is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2023-02-20T17:55:55.097+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2297, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 240, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 170, in default
    return super().default(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Index is not JSON serializable
[2023-02-20T17:55:55.109+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=csv_to_postgres_v01, task_id=df_to_postgres, execution_date=20230220T175548, start_date=20230220T175554, end_date=20230220T175555
[2023-02-20T17:55:55.118+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 170 for task df_to_postgres (Object of type Index is not JSON serializable; 3738)
[2023-02-20T17:55:55.165+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-20T17:55:55.181+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
