[2023-02-14T14:15:39.338+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag_v1_04.insert_into_postgres_table manual__2023-02-14T14:15:38.102717+00:00 [queued]>
[2023-02-14T14:15:39.345+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag_v1_04.insert_into_postgres_table manual__2023-02-14T14:15:38.102717+00:00 [queued]>
[2023-02-14T14:15:39.345+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-14T14:15:39.346+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 6
[2023-02-14T14:15:39.346+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-14T14:15:39.355+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): insert_into_postgres_table> on 2023-02-14 14:15:38.102717+00:00
[2023-02-14T14:15:39.362+0000] {standard_task_runner.py:55} INFO - Started process 10201 to run task
[2023-02-14T14:15:39.365+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag_v1_04', 'insert_into_postgres_table', 'manual__2023-02-14T14:15:38.102717+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpesgek6q7']
[2023-02-14T14:15:39.367+0000] {standard_task_runner.py:83} INFO - Job 99: Subtask insert_into_postgres_table
[2023-02-14T14:15:39.419+0000] {task_command.py:388} INFO - Running <TaskInstance: postgres_operator_dag_v1_04.insert_into_postgres_table manual__2023-02-14T14:15:38.102717+00:00 [running]> on host 01550fe0586b
[2023-02-14T14:15:39.465+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=tlysenko
AIRFLOW_CTX_DAG_ID=postgres_operator_dag_v1_04
AIRFLOW_CTX_TASK_ID=insert_into_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2023-02-14T14:15:38.102717+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-14T14:15:38.102717+00:00
[2023-02-14T14:15:39.466+0000] {sql.py:254} INFO - Executing: 
            INSERT INTO dag_runs(dt, dag_id) values(2023-02-14, postgres_operator_dag_v1_04)
        
[2023-02-14T14:15:39.473+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-02-14T14:15:39.579+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-02-14T14:15:39.595+0000] {sql.py:375} INFO - Running statement: 
            INSERT INTO dag_runs(dt, dag_id) values(2023-02-14, postgres_operator_dag_v1_04)
        , parameters: None
[2023-02-14T14:15:39.599+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "postgres_operator_dag_v1_04" does not exist
LINE 2: ...SERT INTO dag_runs(dt, dag_id) values(2023-02-14, postgres_o...
                                                             ^

[2023-02-14T14:15:39.620+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_operator_dag_v1_04, task_id=insert_into_postgres_table, execution_date=20230214T141538, start_date=20230214T141539, end_date=20230214T141539
[2023-02-14T14:15:39.647+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 99 for task insert_into_postgres_table (column "postgres_operator_dag_v1_04" does not exist
LINE 2: ...SERT INTO dag_runs(dt, dag_id) values(2023-02-14, postgres_o...
                                                             ^
; 10201)
[2023-02-14T14:15:39.698+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-14T14:15:39.724+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
