[2023-02-14T10:06:14.447+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_task_flow_v1.0.get_name manual__2023-02-14T10:06:13.381573+00:00 [queued]>
[2023-02-14T10:06:14.456+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_task_flow_v1.0.get_name manual__2023-02-14T10:06:13.381573+00:00 [queued]>
[2023-02-14T10:06:14.456+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-14T10:06:14.457+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 6
[2023-02-14T10:06:14.457+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-14T10:06:14.466+0000] {taskinstance.py:1300} INFO - Executing <Task(_PythonDecoratedOperator): get_name> on 2023-02-14 10:06:13.381573+00:00
[2023-02-14T10:06:14.473+0000] {standard_task_runner.py:55} INFO - Started process 30522 to run task
[2023-02-14T10:06:14.477+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_task_flow_v1.0', 'get_name', 'manual__2023-02-14T10:06:13.381573+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_task_flow.py', '--cfg-path', '/tmp/tmpplyr13hi']
[2023-02-14T10:06:14.486+0000] {standard_task_runner.py:83} INFO - Job 25: Subtask get_name
[2023-02-14T10:06:14.594+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_task_flow_v1.0.get_name manual__2023-02-14T10:06:13.381573+00:00 [running]> on host 38744fc0668d
[2023-02-14T10:06:14.668+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=tlysenko
AIRFLOW_CTX_DAG_ID=dag_with_task_flow_v1.0
AIRFLOW_CTX_TASK_ID=get_name
AIRFLOW_CTX_EXECUTION_DATE=2023-02-14T10:06:13.381573+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-14T10:06:13.381573+00:00
[2023-02-14T10:06:14.670+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_task_flow.py", line 17, in get_name
    return Jerry
NameError: name 'Jerry' is not defined
[2023-02-14T10:06:14.682+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_task_flow_v1.0, task_id=get_name, execution_date=20230214T100613, start_date=20230214T100614, end_date=20230214T100614
[2023-02-14T10:06:14.693+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 25 for task get_name (name 'Jerry' is not defined; 30522)
[2023-02-14T10:06:14.731+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-14T10:06:14.766+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
